### ISSUE TITLE
3LAS stream

### ISSUE THREAD

**Issue by zygmund2000** [NoobishSVK/fm-dx-webserver#13]
Current implementation of sound works but very unstable and mono, I've modified to stereo but still it is unstable too much sound drops on chrome and firefox.

**Comment by NoobishSVK** [comment]
What's your hardware? Seems to work fine my Android phone, Linux laptop and a Windows PC.

**Comment by zygmund2000** [comment]
It doesn't matter witch hardware I use to test laptop or smartphone because sound drop are always, sometimes it makes crash all node and I need to restart all. My platform for serve is linux but I think you are using windows because parameter for ffmpeg -dshow is windows sound api, please try linux.

**Comment by NoobishSVK** [comment]
There are predefined defaults coming for linux via alsa and we're currently fiddling with the buffer settings, I will notify you once the commit gets published.

**Comment by andimik** [comment]
Yes, please, I am interested, too.

**Comment by NoobishSVK** [comment]
There is a new script for Linux, WAV fallback has also been disabled for Windows. Is there any noticeable change?

**Comment by NoobishSVK** [comment]
It seems like you have opened a ticket directly with the 3LAS developer - the issue should be solved during the weekend, let's hope for the best!

**Comment by NoobishSVK** [comment]
Are there any improvements with the latest commit? I have merged some changes from 3LAS directly.

**Comment by zygmund2000** [comment]
Yes now it is very good so u can mark it as solved.
