### ISSUE TITLE
Make Play/stop button more visible

### ISSUE THREAD

**Issue by PE5PVB** [NoobishSVK/fm-dx-webserver#14]
Some users overlooked the play/stop button. Maybe, make it in a round shape at the topcorner of the screen. Don't use a pause sign, but a stop sign when stream is disabled by the user.

**Comment by NoobishSVK** [comment]
Fixed with https://github.com/NoobishSVK/fm-dx-webserver/commit/525ae519d7b6f257c4f0e2b293d1edb8d78c7746

**Comment by PE5PVB** [comment]
Yup.
