### ISSUE TITLE
Cannot tune with a password if the tuner is locked.

### ISSUE THREAD

**Issue by Overland-DX** [NoobishSVK/fm-dx-webserver#41]
![bilde](https://github.com/NoobishSVK/fm-dx-webserver/assets/102610897/e0dfaa31-9d30-4202-b1d7-1dadeaf2b3ad)

It may appear that I do not have the opportunity to tune when I am logged in with the tune password or admin password when the tuner is locked.
This is either if it is locked to admin or if you have not ticked the option "allow tuner control without password"

**Comment by NoobishSVK** [comment]
I have checked in 1.1.3 and this seems to work. 

Tuner Lock enabled = I was only able to tune as an admin
Allow tuner control without password disabled = I was able to tune with either tune/admin password.

**Comment by Overland-DX** [comment]
oki, i have locked me server for password only: The password is: changeme
Please take a look at my server.
http://overland.fmdx.no:45990/

**Comment by NoobishSVK** [comment]
Seems like it's a serialport issue. I will look into this further.

**Comment by NoobishSVK** [comment]
Please try now, seems to be fixed with 1.1.6.

**Comment by NoobishSVK** [comment]
Locking the issue since there have bene no answers for over a week. Please reopen it if the problem still occurs for you.
