### ISSUE TITLE
Default frequency at startup issue

### ISSUE THREAD

**Issue by stailus** [NoobishSVK/fm-dx-webserver#42]
At startup, the tuner goes to the default frequency even if the option in the setup is not activated. The tuner is set to the default frequency (88.8 Mhz in my case), but it shows 87.5 Mhz

![image](https://github.com/NoobishSVK/fm-dx-webserver/assets/19729347/ebf5e962-47bc-4fbe-88a7-7f768dd24bf6)

![image](https://github.com/NoobishSVK/fm-dx-webserver/assets/19729347/39bbbe89-4215-484c-b754-593b573acba8)

![image](https://github.com/NoobishSVK/fm-dx-webserver/assets/19729347/3d2f5ce2-9bf1-404f-943c-dc733acfd2da)

**Comment by NoobishSVK** [comment]
I made a few changes, it should work properly now without tuning to the defaultFreq.

**Comment by stailus** [comment]
Yes is ok now.

**Comment by stailus** [comment]
Now if I set default freq on, webserver don't start...

![image](https://github.com/NoobishSVK/fm-dx-webserver/assets/19729347/1e36a456-3cde-4330-8f32-a37e3c5c8247)

**Comment by NoobishSVK** [comment]
Should be fixed with v1.1.9, please check.

**Comment by stailus** [comment]
Yes is ok now.
