### ISSUE TITLE
The AF list is not cleared at rds reset

### ISSUE THREAD

**Issue by stailus** [NoobishSVK/fm-dx-webserver#46]
When r is pressed on a station with RDS, the AF list in the UI doubles, triples, etc. as in the picture below

![image](https://github.com/NoobishSVK/fm-dx-webserver/assets/19729347/b0abd7a7-e1c1-471b-8b1b-a014b1cc97ae)

**Comment by NoobishSVK** [comment]
Thanks for reporting, will be fixed with the next commit.

**Comment by stailus** [comment]
Is ok now. Thank you!
