### ISSUE TITLE
Sound is boosted twice

### ISSUE THREAD

**Issue by zygmund2000** [NoobishSVK/fm-dx-webserver#48]
Something is wrong with audio - it starts at normal volume but after while (~1s) sounds like double boost and it overdrive with lot of thd.

**Comment by NoobishSVK** [comment]
Sorry for the delay. I have decided to change the script a bit, so I hope it will help. I will let you know once the update is out.

**Comment by NoobishSVK** [comment]
Please check, I made some changes.

**Comment by zygmund2000** [comment]
Problem still exists it looks like script sets audio in TEF at +10db  averytime it starts

**Comment by NoobishSVK** [comment]
I see now. I have talked about this on the DIscord with PE5PVB and this is a bug of their firmware, you will need to consult it with them or make an Issue ticket there. Therefore I'm closing the ticket as it's not related to the webserver directly.
