### ISSUE TITLE
Accessibility: Hiding the Chat area using the keyboard not possible

### ISSUE THREAD

**Issue by marvellousmachine** [NoobishSVK/fm-dx-webserver#51]
Currently it is not possible to hide the chat area using the keyboard. It would be great if the element was assigned an ARIA button role with the "Hide Chat" label:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role

**Comment by NoobishSVK** [comment]
I have added a role="button" attribute to the close tag, it will be available in the next update, let me know if that helps.

**Comment by marvellousmachine** [comment]
The button is there, it just needs a label now. :)

**Comment by NoobishSVK** [comment]
Please try now, i have added a tabindex.

**Comment by marvellousmachine** [comment]
Fixed. Thanks.
