### ISSUE TITLE
Ignore keyboard shortcuts also in the Frequency edit box

### ISSUE THREAD

**Issue by marvellousmachine** [NoobishSVK/fm-dx-webserver#53]
Currently it's not possible to use the keyboard arrows in the Frequency edit box to move through numbers without also changing the frequency. Consider ignoring the keyboard shortcuts in this edit box, just like in the Chat area edit boxes or on the volume slider.

**Comment by marvellousmachine** [comment]
TBH, this is only a very minor issue for me, I don't need to edit the imput that often and it's still possible with the side effect of tuning simultaneously.

**Comment by NoobishSVK** [comment]
In that case I am closing this issue for now. 
If it helps, the best way for me to change the frequency in case I mess up is just straight up CTRL+A and DEL. :)
