### ISSUE TITLE
Accessibility: Not possible to close the Settings panel using keyboard

### ISSUE THREAD

**Issue by marvellousmachine** [NoobishSVK/fm-dx-webserver#56]
Similarly to #51, it is not possible to close the Settings panel using the keyboard. Please add the button role with the appropriate label here as well and make sure for it to receive focus when tabbing / Shift+tabbing.

**Comment by NoobishSVK** [comment]
I have added roles and aria labels for this, would it be possible for you to check? Thanks!

**Comment by marvellousmachine** [comment]
Works great. Would it be possible to make it focusable when tabbing as well?

**Comment by NoobishSVK** [comment]
I have added the tabindex option, would you mind trying it out? Thank you!

**Comment by marvellousmachine** [comment]
Fixed. Thanks.
