### ISSUE TITLE
Frequency at first start always 87.5 MHz

### ISSUE THREAD

**Issue by andimik** [NoobishSVK/fm-dx-webserver#6]
see https://discord.com/channels/1053804249651359765/1170013490661048411/1199129935286124646 and below.

At the first start, the shown frequency is always 87.5 MHz, and not the tuned frequency, although there is a T-Line:

![grafik](https://github.com/NoobishSVK/fm-dx-webserver/assets/24510556/bcf48dc7-dd34-4487-90ed-70a64f983510)

```
zlwncigaiccimbrz
67bb5dc9eeacde1d4a75578491d3aefdd270c5e3
x
o1,0
Ss53.1, 3, 29
Pa213
R2000496e646900
OK
T102900
Ss53.1, 4, 29
Pa213
R8003f2058c4e00
Ss53.0, 3, 29
Pa213
R001887a1202000
Ss53.0, 3, 29
Pa213
Ss53.0, 3, 29
Pa213
R2001652d506f00
```

**Comment by NoobishSVK** [comment]
Please check it now, should be fixed with [5ab4a39](https://github.com/NoobishSVK/fm-dx-webserver/commit/5ab4a39bd545b38521dcac2d448b1fb8c0baabe2)
