### ISSUE TITLE
More strict processing of keyboard shortcuts

### ISSUE THREAD

**Issue by marvellousmachine** [NoobishSVK/fm-dx-webserver#63]
Currently the keyboard shortcuts are processed quite loosely, what can lead to undesired behaviour. E.G.:

1. Closing the window using Alt+F4 also activates the preset saved under F4 and closes the window.
2. pressing Ctrl+R resets the RDS data before refresing the page

The desired behaviour would be to strictly react only to defined shortcuts, in this case F4, R, and also arrows without modifiers. It might be also useful in the future when defining additional shortcuts.

**Comment by NoobishSVK** [comment]
I have added a check for modifier keys, please check.

**Comment by marvellousmachine** [comment]
Fixed. Thanks.
