### ISSUE TITLE
Broadcasting location wrongly identifed in some cases.

### ISSUE THREAD

**Issue by numerci** [NoobishSVK/fm-dx-webserver#68]
Close to my WebServer the same station broadcast on the same frequency. One is 34Km away and the second one 82Km away. Due to the terain I am only getting signal from the distant location (82Km) but in the WebServer the broadcast is always identifed as the one 34Km away. 

A way of manually overwite the broadcast location should be available on the WebServer. The owner of course it knows about what is received but the guests is very likely not to know what is actually being received.

**Comment by NoobishSVK** [comment]
Hello, currently this alrogithm counts the most likely TX based on a logarithmic scale. Big changes are coming including terrain calculation, therefore it should be way more accurate in the near future.
