### ISSUE TITLE
CSS design bug on hover

### ISSUE THREAD

**Issue by AmateurAudioDude** [NoobishSVK/fm-dx-webserver#84]
As mentioned. See attached image:

![image](https://github.com/user-attachments/assets/19766bfd-fd46-472d-a565-9fd2a34be29c)

**Comment by NoobishSVK** [comment]
Fixed with 1.2.8, can you please check?

**Comment by AmateurAudioDude** [comment]
Yes it looks good now. However, a new visual bug with the latest version, extra PI code spacing: 

![image](https://github.com/user-attachments/assets/cbeee5fb-257e-4e20-89b1-b6c2938a5cf2)

**Comment by AmateurAudioDude** [comment]
Fix is
```<h2 class="signal-heading">PI CODE</h2>```

**Comment by AmateurAudioDude** [comment]
It's good now. The visual bug appeared when the browser height was below 860px.
