### ISSUE TITLE
Cant login tuner password

### ISSUE THREAD

**Issue by laarhoven1** [NoobishSVK/fm-dx-webserver#91]
after set tuner password notable to tune the radio still locked.!!
after set password and (re) start the sever.

if set no password also not able to tune .
FM-DX Webserver v1.3.0.1 [15/9/2024]

**Comment by NoobishSVK** [comment]
Hello, where did you enable the lock / unlock? Don't forget there are two switches. One is directly in the admin panel and the other one is in the admin dashboard in the panel on the right side.

**Comment by laarhoven1** [comment]
Thx this solved the problem.
